#!/bin/bash

# Use Puppet command to ensure git is installed
puppet resource package git ensure=present

# Use Puppet command to ensure apache2 service is installed and running 
puppet resource service apache2 ensure=running 

# Use Puppet command to remove directory /tmp/6269405p/work and recreate directory /tmp/6269405p/work
puppet resource file /tmp/6269405p/work ensure=absent force=true
puppet resource file /tmp/6269405p/work ensure=directory 

# Clone 6269405p_poc_repo to container’s /tmp/6269405p/work
cd /tmp/6269405p/work
git clone https://github.com/RP23003387/POC_REPO.git

# Copy new index.html to replace /var/www/html/index.html
puppet resource file /var/www/html/index.html ensure=absent
puppet resource file /var/www/html/index.html ensure=file source=/tmp/6269405p/work/POC_REPO/index.html
